config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :garage_items

end

app/models/garage_item.rb
class GarageItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/garage_items_controller.rb
class GarageItemsController < ApplicationController

	def index
		@garage_items = GarageItem.all
	end

	def new
		@new_garage_item = GarageItem.new
	end

	def create
		@new_garage_item = GarageItem.new(garage_item_params)
		if @new_garage_item.save
			redirect_to garage_items_path
		else
			redirect_to new_garage_item_path
		end
	end

	def show
		@garage_item = GarageItem.find(params[:id])
	end

	def edit
		@garage_item = GarageItem.find(params[:id])
	end

	def update
		@garage_item = GarageItem.find(params[:id])
		if @garage_item.update_attributes(garage_item_params)
				redirect_to garage_item_path(@garage_item)
		end
	end

	def destroy
		@garage_item = GarageItem.find(params[:id])
		if @garage_item.destroy
			redirect_to garage_items_path
		else
			redirect_to garage_item_path(@garage_item)
		end
	end

	def change_unsold
		@garage_item = GarageItem.find(params[:id])
		if @garage_item.unsold
			val = true
		else
			val = false
		end
		@garage_item.update_attributes(:unsold => val)
		redirect_to garage_items_path
	end

	# def status
	# 	if @garage_item.unsold = true
	# 		puts "Unsold"
	# 	else
	# 		puts "Sold"
	# 	end
	# end

	private

	def garage_item_params
		params.require(:garage_item).permit!
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garage_items_helper.rb
module GarageItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/garage_items/_form.html.haml
%link{ :href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :type => "text/css", :rel => "stylesheet" }

= f.label :category
= f.text_field :category
%br
= f.label :headline 
= f.text_field :headline
%br
= f.label :price
= f.text_field :price
%br
= f.label :condition
= f.text_field :condition
%br
= f.label :description
= f.text_area :description
%br
= f.label "Date"
= f.date_select :submit_date
%br
= f.label "Unsold"
= f.radio_button :unsold, true
%br
= f.label "Sold"
= f.radio_button :unsold, false
%br
= f.submit "Save"

app/views/garage_items/edit.html.haml
%link{ :href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :type => "text/css", :rel => "stylesheet" }

= form_for @garage_item, url: "/garage_items/#{@garage_item.id}" do |f|
	= render "form", f: f

%br
= button_to "Go Back to Home", garage_items_path, method: "get"

app/views/garage_items/index.html.haml
%link{ :href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :type => "text/css", :rel => "stylesheet" }

%h1 Garage Sale Items

%table.table.striped
  %thead
    %tr
      %th Category
      %th Headline
      %th Price
      %th Condition
      %th Description
      %th Date As Of
      %th Sold?
      %th View
      %th Edit
      %th Delete 
  %tbody
    - @garage_items.each do |g|
      %tr
        %td= g.category
        %td= g.headline
        %td= number_to_currency(g.price)
        %td= g.condition
        %td= g.description
        %td= g.submit_date
        %td= g.unsold
        %td= link_to "View", garage_item_path(g)
        %td= link_to "Edit", edit_garage_item_path(g)
        %td= link_to "Delete", garage_item_path(g), method: "delete", :data => { :confirm => 'Are you sure?' }
%br

= button_to 'Add New Item', new_garage_item_path, method: "get"
%br
%br

app/views/garage_items/new.html.haml
%link{ :href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :type => "text/css", :rel => "stylesheet" }

%h1 New Garage Item

=	form_for @new_garage_item, url: "/garage_items" do |f|
	= render "form", f: f

%br
= button_to 'Back', garage_items_path, method: "get"

app/views/garage_items/show.html.haml
%link{ :href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :type => "text/css", :rel => "stylesheet" }

%p#notice= notice

%p
  %b Category:
  = @garage_item.category
%p
  %b Headline:
  = @garage_item.headline
%p
  %b Price:
  = number_to_currency(@garage_item.price)
%p
  %b Condition:
  = @garage_item.condition
%p
  %b Description:
  = @garage_item.description
%p
  %b Date As Of:
  = @garage_item.submit_date
%p
  %b Sold?
  = @garage_item.unsold

= link_to 'Edit', edit_garage_item_path, method: "get"
\|
= link_to 'Back', garage_items_path, method: "get"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Garager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>